### ISSUE TITLE
blktap build fails from xenserver/xenserver-build-env

### ISSUE THREAD

**Issue by rushikeshjadhav** [xapi-project/blktap#249]
How to reproduce :

[root@localhost ~]# ./run.py -p blktap
Launching docker with args ['docker', 'run', '-i', '-t', '-u', 'builder', '-e', 'PACKAGES=blktap', 'xenserver/xenserver-build-env', '/usr/local/bin/init-container.sh']
.
.
.

sh-4.2$ ls
local-SRPMs
sh-4.2$ cd local-SRPMs/
sh-4.2$ ls
blktap-3.7.0-1.0.src.rpm
sh-4.2$ rpmbuild --rebuild blktap-3.7.0-1.0.src.rpm 
Installing blktap-3.7.0-1.0.src.rpm
.
.
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -D_GNU_SOURCE -I../include  -Wall -Werror -DXC_WANT_COMPAT_EVTCHN_API -DXC_WANT_COMPAT_GNTTAB_API  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c -o tapdisk-control.lo tapdisk-control.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -D_GNU_SOURCE -I../include -Wall -Werror -DXC_WANT_COMPAT_EVTCHN_API -DXC_WANT_COMPAT_GNTTAB_API -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -c tapdisk-control.c  -fPIC -DPIC -o .libs/tapdisk-control.o
In file included from td-blkif.h:43:0,
                 from tapdisk-vbd.h:40,
                 from tapdisk-control.c:53:
td-req.h:37:24: fatal error: xen/gntdev.h: No such file or directory
 #include <xen/gntdev.h>
                        ^
compilation terminated.

###################

gntdev.h is present at path /usr/include/xen/sys/gntdev.h

**Comment by MarkSymsCtx** [comment]
/usr/include/xen/gntdev.h is provided by the kernel-headers, /usr/include/xen/sys/gntdev.h is from the xen-devel package. blktap should be building against the kernel headers and it looks like you don't have these installed.

**Comment by MarkSymsCtx** [comment]
It does look like the `blktap.spec.in` is missing a number of BuildRequires (probably because Citrix doesn't use this spec.

**Comment by MarkSymsCtx** [comment]
PR https://github.com/xapi-project/blktap/pull/250 may help here.

**Comment by rushikeshjadhav** [comment]
I have kernel headers & devel installed. Problem still persists. My blktap.spec is inline to PR #250.

sh-4.2$ rpm -qa | grep kernel
kernel-headers-3.10.0-862.3.2.el7.x86_64
kernel-devel-3.10.0-862.3.2.el7.x86_64
sh-4.2$ rpm -qa | grep xen
xen-devel-4.7.5-6.0.2.x86_64
xen-hypervisor-4.7.5-6.0.2.x86_64
xen-dom0-libs-4.7.5-6.0.2.x86_64
xen-dom0-libs-devel-4.7.5-6.0.2.x86_64
xen-libs-4.7.5-6.0.2.x86_64
xen-libs-devel-4.7.5-6.0.2.x86_64

I think issue is in include it self. I can see that the file gntdev.h exists at 
sh-4.2$ locate gntdev
/usr/include/xen/sys/gntdev.h
/usr/src/kernels/3.10.0-862.3.2.el7.x86_64/include/xen/gntdev.h

sh-4.2$ sudo yum provides */xen/gntdev.h
suggests kernel-devel and kernel-debug-devel.

Probably build system is not referring the include path "/usr/src/kernels/3.10.0-862.3.2.el7.x86_64/include"

**Comment by MarkSymsCtx** [comment]
/usr/include/xen/sys/gntdev.h is the wrong version of the include, you need the one from /usr/include/xen/gntdev.h which is provided by the kernel.

**Comment by MarkSymsCtx** [comment]
`rpm` -ql kernel-headers-3.10.0-862.3.2.el7.x86_64 | grep xen` ?

**Comment by rushikeshjadhav** [comment]
sh-4.2$ rpm -ql kernel-headers-3.10.0-862.3.2.el7.x86_64 | grep xen
/usr/include/xen
/usr/include/xen/evtchn.h
/usr/include/xen/privcmd.h

The package is delivered from @updates repo.

**Comment by MarkSymsCtx** [comment]
Ah, of course. The upstream Linux 3.10 kernel doesn't contain gntdev.h but the Citrix provided XenServer 3.10 kernel does. You need the kernel-headers from XenServer or build against a 4.9 kernel which contains gntdev.

**Comment by rushikeshjadhav** [comment]
Thanks for clarification. I could build the package with 4.9 kernel.
